name: flutter_login_facebook
description: Login via Facebook. Easily add Facebook login feature in your application. User profile information included.
version: 3.0.0
homepage: https://github.com/gtech-mobiledev/flutter_login_facebook
repository: https://github.com/gtech-mobiledev/flutter_login_facebook

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  list_ext: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  innim_lint: ^0.4.0

flutter:
  plugin:
    platforms:
      android:
        package: ru.innim.flutter_login_facebook
        pluginClass: FlutterLoginFacebookPlugin
      ios:
        pluginClass: FlutterLoginFacebookPlugin
